# dbt_project:
#   outputs:
#     dev:
#       account: https://jdcxdrv-jw41110.snowflakecomputing.com
#       database: DBT_First_Project
#       password: MONIchai1234!@
#       role: ACCOUNTADMIN
#       schema: DETAILS
#       threads: 1
#       type: snowflake
#       user: Chaitalykundu
#       warehouse: compute_wh
#   target: dev

dbt_project:
  outputs:
    dev:
      account: jdcxdrv-jw41110
      database: DBT_FIRST_PROJECT
      password: MONIchai1234!@
      role: ACCOUNTADMIN
      schema: second
      threads: 10
      type: snowflake
      user: Chaitalykundu
      warehouse: COMPUTE_WH
  target: dev
